---
- name: Fetch Syncthing configuration
  fetch:
    src="{{syncthing_user_home}}/{{item}}"
    dest="{{syncthing_fetch_dir}}"
    fail_on_missing=yes
  with_items:
    - ".local/state/syncthing/cert.pem"
    - ".local/state/syncthing/key.pem"
    - ".local/state/syncthing/config.xml"
    - ".local/state/syncthing/https-cert.pem"
    - ".local/state/syncthing/https-key.pem"
